# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  REPO_NAME: 'vcpkg'
  VCPKG_ROOT: '$(Build.SourcesDirectory)'

pool:
    name: 'MAPAL Design'

steps:
  - task: BatchScript@1
    displayName: 'Bootstrap'
    inputs:
      filename: 'bootstrap-vcpkg.bat'
  
  - script: vcpkg.exe install azure-storage-cpp:x64-windows
    displayName: 'azure-storage-cpp'

  - script: vcpkg.exe install curl[sspi]:x64-windows
    displayName: 'curl[sspi]'

  - script: vcpkg integrate install
    displayName: 'integrate install'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
